[phases.setup]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"

[build.args]
NODE_VERSION = "20"

[build.environment]
NPM_CONFIG_PRODUCTION = "false"
NODE_ENV = "production"
