[phases.setup]
cmds = ["corepack enable pnpm", "pnpm install"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run start"

[build.args]
NODE_VERSION = "18"

[build.environment]
NPM_CONFIG_PRODUCTION = "false"
NODE_ENV = "production"
PNPM_HOME = "/root/.local/share/pnpm"
PATH = "${PNPM_HOME}:${PATH}"
