services:
  - type: web
    name: harmonia-ui
    env: static
    buildCommand: pnpm install && pnpm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.x
    plan: free
